server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service  # Usando Eureka para descubrir el servicio
          predicates:
            - Path=/api/usuario/**
        - id: transaccion-service
          uri: lb://transaccion-service  # Usando Eureka para descubrir el servicio
          predicates:
            - Path=/api/transaccion/**
        - id: solicitud-service
          uri: lb://solicitud-service  # Usando Eureka para descubrir el servicio
          predicates:
            - Path=/api/solicitudPago

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka  # URL del servidor Eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info


